<template>
  <div class="head-nav">
    <img src="logo.png" alt="asd" class="logo-img" />
      <a class="head-nav-call-to-action" :href="`tel:+${mobile}`">
              052-550-3666
      <img src="call.svg" alt="asd" class="call" />
        </a>
              <a class="head-nav-call-absolute-to-action" :href="`tel:+${mobile}`">
              052-550-3666 חייג אלינו עכשיו
      <img src="call.svg" alt="asd" class="call1 vibrate-1" />
        </a>

  </div>
</template>

<script>
import httpService from "../services/httpService";
import logEventsService from "../services/logEventsService";
export default {
  name: "head-nav",

  data() {
    return {
      mobile: "972525503666",
    };
  },
  methods: {
    onGoToForm() {
      // httpService.post("/log-events", {
      //   url: window.location.href,
      //   name: "goToForm",
      //   vertical: "dentist",
      //   hostname: window.location.hostname,
      //   referrer: document.referrer,
      // });
      logEventsService.newLog("goToForm");
    },
  },
};
</script>

<style scoped>
.head-nav {
  z-index: 9;
  background-color: #fff;
  position: fixed;
  top: 0px;
  left: 0px;
  width: 100%;
  height: 80px;
  padding: 24px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  /* background-color: red; */
}

.logo-img {
  height: 70px;
  width: auto;
}
.call {
  margin-right: 6px;
  height: 22px;
}
.call1 {
  margin-right: 20px;
  height: 22px;
}

.head-nav-call-to-action {
  position: fixed;
  left: 9px;
  top: 20px;
  padding: 7px 15px;
  font-family: Segoe UI;
  font-style: normal;
  font-size: 20px;
  line-height: 19px;
  text-align: center;
  background: rgba(0, 72, 255, 0.603);
  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
  color: #ffffff;
  font-weight: 500;
  text-decoration: none;
}
.head-nav-call-to-action:hover {
  background-color: rgba(0, 72, 255, 0.774);
}

.head-nav h3 {
  font-weight: bolder;
  font-size: 11px;
  line-height: 14px;
}

.vibrate-1 {
  -webkit-animation: vibrate-1 0.3s linear infinite both;
  animation: vibrate-1 0.3s linear infinite both;
}
.head-nav-call-absolute-to-action{
  position: fixed;
  bottom: 0px;
  height: 60px;
  width: 100vw;
  background-color: rgb(15, 155, 33);
  display: flex;
  justify-content: center;
  align-items: center;
  font-weight: 900;
  color: #fff;
  text-decoration: none;
}


.vibrate-1 {
	-webkit-animation: vibrate-1 0.3s linear infinite both;
	        animation: vibrate-1 0.3s linear infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-8-14 1:54:50
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation vibrate-1
 * ----------------------------------------
 */
@-webkit-keyframes vibrate-1 {
  0% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
  20% {
    -webkit-transform: translate(-2px, 2px);
            transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(-2px, -2px);
            transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, 2px);
            transform: translate(2px, 2px);
  }
  80% {
    -webkit-transform: translate(2px, -2px);
            transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
}
@keyframes vibrate-1 {
  0% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
  20% {
    -webkit-transform: translate(-2px, 2px);
            transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(-2px, -2px);
            transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, 2px);
            transform: translate(2px, 2px);
  }
  80% {
    -webkit-transform: translate(2px, -2px);
            transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
}

</style>
